/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CartImport } from './routes/Cart'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CartRoute = CartImport.update({
  path: '/Cart',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, CartRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Cart"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Cart": {
      "filePath": "Cart.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
